security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: INFO
    com:
      netflix:
        eureka: OFF #OFF
        discovery: OFF #OFF

spring: # <---NEW SECTION
  cloud:
    services:
      registrationMethod: direct #direct #route

ribbon: # <---NEW SECTION
  IsSecure: false

#spring:
#  rabbitmq:
#    addresses: ${vcap.services.cloud-bus.credentials.http_api_uris:http://localhost:5672}
